const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  "La maîtresse de cérémonie de la 46e édition des César qui se tiendra le 12 mars s'est exprimée au micro de France Inter. Elle y revient sur les épreuves traversées depuis un an par le septième art français. Et évoque la politique du gouvernement à l'égard du monde du spectacle.",
  "Alors que la journaliste de France Inter n'a pas manqué de saluer le courage de l'actrice qui a accepté d'animer une cérémonie largement ternie l'an dernier par le César donné à Roman Polanski et le départ théâtral d'Adèle Haenel de la salle Pleyel, Marina Foïs s'est montrée assez sereine: «Je pense que les crises familiales sont inévitables et intéressantes. Au niveau de l'Académie, de son règlement, de ses futurs statuts, on a changé beaucoup de choses. La parité c'est OK, toutes les instances de l'Académie sont rigoureusement paritaires. Il y a un gros travail à faire encore sur la diversité, et sur le collège des votants, qui est de 4.500 personnes dont 64 % d'hommes. En diversifiant cette population, les votes seront différents et les gagnants ne seront plus les mêmes.»",
  "Elle n'en demeure pas moins très critique à l'égard du gouvernement et, plus spécialement, de sa gestion du secteur culturel mis à mal par la pandémie. Interrogée sur la colère des professionnels du spectacle tous secteurs confondus, qui ont appelé aujourd'hui l'État à «changer de méthode» pour «déconfiner la culture», l'actrice n'a pas ménagé ses propos.«C'est la moindre des choses d'avoir un calendrier et des perspectives, sinon c'est un mépris grave. Ça fait un an qu'on est fermés, tous les “on croise les doigts” sont d'une grande violence et une grande approximation. Assumez le choix qui est le vôtre : nous fermons les lieux culturels au profit de certains autres. Si on nous dit “on n'a pas le choix”, on est méprisés.»",
  "Marina Foïs aime donc sa «famille» et compte bien le prouver le 12 mars prochain, appuyée par les truculents Blanche Gardin et Laurent Lafitte pour l'écriture de ses textes. Malgré la pandémie qui impose une cérémonie sans public, elle fera en sorte «que la scène ressemble à une cérémonie normale, il y aura des remettants et des gagnants, un orchestre dirigé par Benjamin Biolay…». Sans oublier d'insuffler ce savant mélange de bonne humeur et de réflexion, l'actrice comptant s'en remettre à la fameuse règle des trois ''D'' d'Alain Chabat : «Danse, dénonce, déconne.»",
  "La première chanson du disque, Je ne sais pas si c’est tout le monde, donne son titre au premier film de l’artiste. Une œuvre intense et contemplative dans laquelle interviennent personnalités connues (Jean Rochefort dans sa dernière apparition à l’écran, Alain Souchon et Aloïse Sauvage) et anonymes. Au fil des années, Delerm, touche à tout inspiré (chanson, théâtre, photo, et cinéma donc) tisse un fil attachant et singulier qui le relie à un public fervent et fidèle. Lequel s’impatiente de le retrouver sur scène, où il excelle à chaque fois",
];
export default text;
